# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('syntax', models.CharField(choices=[('java', 'JAVA'), ('ruby', 'RUBY'), ('python', 'PYTHON'), ('html', 'HTML'), ('c', 'C')], default='python', max_length=10)),
                ('paste', models.TextField()),
                ('slug', models.SlugField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
