# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20160701_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='style',
        ),
    ]
